Bump sdk version + fix hvs breaking changes
hashicorp/terraform-provider-hcp pull request #1122
Opened 2024-10-17 20:21 UTC by keeefer

### :hammer_and_wrench: Description

Bump sdk version [link](https://github.com/hashicorp/hcp-sdk-go/compare/v0.116.0...v0.117.0). 
Use `name` instead of `secret_name` for rotating secrets.

### :building_construction: Acceptance tests

- [ ] Are there any feature flags that are required to use this functionality?
- [ ] Have you added an acceptance test for the functionality being added?
- [ ] Have you run the acceptance tests on this branch?

Output from acceptance testing:

```sh
$ make testacc TESTARGS='-run=TestAccXXX'

...
```

2024-10-17 20:40 UTC, dhuckins approved these changes

2024-10-17 20:48 UTC, averche approved these changes
Looks good! Are there any responses that need to be adjusted as well (e.g. for [MongoDB](https://github.com/hashicorp/cloud-vault-secrets/pull/2227/files#diff-3b9d0c50f151ac8ab6bc650d911b878f4b7be63aed51c2572efe0cf2c3d4c53aL2245-L2248))?

2024-10-17 22:41 UTC, keeefer commented
> Looks good! Are there any responses that need to be adjusted as well (e.g. for [MongoDB](https://github.com/hashicorp/cloud-vault-secrets/pull/2227/files#diff-3b9d0c50f151ac8ab6bc650d911b878f4b7be63aed51c2572efe0cf2c3d4c53aL2245-L2248))?

afaik that was covered here [pr](https://github.com/hashicorp/terraform-provider-hcp/pull/1113/files#diff-5f19d406117b30f457b92cf62a85ab9ebd988eaebe9321703109a3c985b5cd98R72-R81)

2024-10-18 02:55 UTC, averche commented on internal/provider/vaultsecrets/data_source_vault_secrets_rotating_secret.go
> +	Name           types.String `tfsdk:"name"`
I think we should leave this as SecretName since this is part of the TF provider data source API. Changing it will break existing TF configs.

2024-10-18 03:00 UTC, averche requested changes
I believe the above might be a breaking change

2024-10-18 13:43 UTC, pierluc-codes commented
> I believe the above might be a breaking change

I know that the version is pre 1.0 and according to symver we can push breaking change but we should consider to keep thing as they are.

2024-10-22 17:07 UTC, averche approved these changes

2024-10-22 17:49 UTC, keeefer commented on .changelog/1122.txt
> +```
Ah good point, ill update

2024-10-23 16:29 UTC, jasonpilz approved these changes
Thanks

2024-10-23 19:45 UTC, merged