Azure Peering Guide
hashicorp/terraform-provider-hcp pull request #712
Opened 2023-12-20 04:16 UTC by jasonpilz

### :hammer_and_wrench: Description

2024-01-04 22:51 UTC, jasonpilz commented on docs/resources/azure_peering_connection.md
> --> **Note:** This data source is currently in public beta.
This is a faulty comment as it is a resource, not data source.

2024-01-05 00:00 UTC, milesjh requested changes
Added a couple additional notes for clarity on what AzureAD/AzureRM permissions are required for the service principal used by the Terraform provider auth.

2024-01-08 18:19 UTC, pierluc-codes approved these changes

2024-01-08 19:27 UTC, jasonpilz commented
> Added a couple additional notes for clarity on what AzureAD/AzureRM permissions are required for the service principal used by the Terraform provider auth.

Thanks! Have added those suggestions.

2024-01-08 19:58 UTC, merged